[jupiter.registry.wh]
    connectTimeout = "1s"
    endpoints=["192.168.174.149:2379"]
    secure = false
[jupiter.client.etcdserver]
# win
    address = "etcd:///main.exe"
# linux
#    address = "etcd:///main.exe"
    balancerName = "round_robin" # 默认值
    block =  false # 默认值
    dialTimeout = "0s" # 默认值

